spring:
  application:
    name: sistema-cadastro-empresa-cliente
  
  datasource:
    url: jdbc:postgresql://localhost:5432/SistemaCadastroAuth
    username: postgres
    password: 123a123a
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# JWT Configuration
jwt:
  secret: mySecretKey12345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 horas em millisegundos
  header: Authorization
  prefix: "Bearer "

# Logging
logging:
  level:
    sys.sistema_cadastro_empresa_cliente: DEBUG
    org.springframework.security: DEBUG

# Server
server:
  port: 8080

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
